import { FieldDef } from './types';

export const FIELD_DEFS: Record<number, FieldDef> = {
  1: { number: 1, name: 'Bitmap (Secondary)', type: 'b', length: 8 },
  2: { number: 2, name: 'Primary Account Number (PAN)', type: 'n', length: 0, variableLength: 'LLVAR', maxLength: 19 },
  3: { number: 3, name: 'Processing Code', type: 'n', length: 6 },
  4: { number: 4, name: 'Amount, Transaction', type: 'n', length: 12 },
  5: { number: 5, name: 'Amount, Settlement', type: 'n', length: 12 },
  6: { number: 6, name: 'Amount, Cardholder Billing', type: 'n', length: 12 },
  7: { number: 7, name: 'Transmission Date and Time', type: 'n', length: 10 },
  8: { number: 8, name: 'Amount, Cardholder Billing Fee', type: 'n', length: 8 },
  9: { number: 9, name: 'Conversion Rate, Settlement', type: 'n', length: 8 },
  10: { number: 10, name: 'Conversion Rate, Cardholder Billing', type: 'n', length: 8 },
  11: { number: 11, name: 'Systems Trace Audit Number (STAN)', type: 'n', length: 6 },
  12: { number: 12, name: 'Time, Local Transaction', type: 'n', length: 6 },
  13: { number: 13, name: 'Date, Local Transaction', type: 'n', length: 4 },
  14: { number: 14, name: 'Date, Expiration', type: 'n', length: 4 },
  15: { number: 15, name: 'Date, Settlement', type: 'n', length: 4 },
  17: { number: 17, name: 'Date, Capture', type: 'n', length: 4 },
  18: { number: 18, name: 'Merchant Type', type: 'n', length: 4 },
  19: { number: 19, name: 'Acquiring Institution Country Code', type: 'n', length: 3 },
  22: { number: 22, name: 'POS Entry Mode', type: 'n', length: 3 },
  23: { number: 23, name: 'Card Sequence Number', type: 'n', length: 3 },
  24: { number: 24, name: 'Network International Identifier', type: 'n', length: 3 },
  25: { number: 25, name: 'Point of Service Condition', type: 'n', length: 2 },
  26: { number: 26, name: 'POS PIN Capture Code', type: 'n', length: 2 },
  32: { number: 32, name: 'Acquiring Institution ID', type: 'n', length: 0, variableLength: 'LLVAR', maxLength: 11 },
  33: { number: 33, name: 'Forwarding Institution ID', type: 'n', length: 0, variableLength: 'LLVAR', maxLength: 11 },
  35: { number: 35, name: 'Track 2 Data', type: 'z', length: 0, variableLength: 'LLVAR', maxLength: 37 },
  37: { number: 37, name: 'Retrieval Reference Number', type: 'an', length: 12 },
  38: { number: 38, name: 'Approval Code', type: 'an', length: 6 },
  39: { number: 39, name: 'Response Code', type: 'an', length: 2 },
  41: { number: 41, name: 'Card Acceptor Terminal ID', type: 'an', length: 8 },
  42: { number: 42, name: 'Card Acceptor ID', type: 'an', length: 15 },
  43: { number: 43, name: 'Card Acceptor Name/Location', type: 'an', length: 40 },
  44: { number: 44, name: 'Additional Response Data', type: 'an', length: 0, variableLength: 'LLVAR', maxLength: 25 },
  48: { number: 48, name: 'Additional Data', type: 'an', length: 0, variableLength: 'LLLVAR', maxLength: 999 },
  49: { number: 49, name: 'Currency Code, Transaction', type: 'n', length: 3 },
  50: { number: 50, name: 'Currency Code, Settlement', type: 'n', length: 3 },
  51: { number: 51, name: 'Currency Code, Cardholder Billing', type: 'n', length: 3 },
  52: { number: 52, name: 'PIN Data', type: 'b', length: 8 },
  53: { number: 53, name: 'Security Related Control Information', type: 'n', length: 16 },
  54: { number: 54, name: 'Amount, Actual', type: 'an', length: 12 },
  55: { number: 55, name: 'ICC Data', type: 'b', length: 0, variableLength: 'LLLVAR', maxLength: 999 },
  62: { number: 62, name: 'Private/Reserved', type: 'an', length: 0, variableLength: 'LLLVAR', maxLength: 999 },
  63: { number: 63, name: 'Private/Reserved', type: 'an', length: 0, variableLength: 'LLLVAR', maxLength: 999 },
  64: { number: 64, name: 'Message Authentication Code (MAC)', type: 'b', length: 8 },
};

export const MTI_LABELS: Record<string, string> = {
  '0100': 'Authorization Request',
  '0110': 'Authorization Response',
  '0120': 'Authorization Advice',
  '0130': 'Authorization Advice Response',
  '0200': 'Financial Request',
  '0210': 'Financial Response',
  '0220': 'Financial Advice',
  '0230': 'Financial Advice Response',
  '0400': 'Reversal Request',
  '0410': 'Reversal Response',
  '0420': 'Reversal Advice',
  '0430': 'Reversal Advice Response',
  '0800': 'Network Management Request',
  '0810': 'Network Management Response',
};

export const RESPONSE_CODES: Record<string, string> = {
  '00': 'Approved',
  '01': 'Refer to Issuer',
  '03': 'Invalid Merchant',
  '05': 'Do Not Honor',
  '12': 'Invalid Transaction',
  '13': 'Invalid Amount',
  '14': 'Invalid Card Number',
  '15': 'No Such Issuer',
  '41': 'Lost Card',
  '43': 'Stolen Card',
  '51': 'Insufficient Funds',
  '54': 'Expired Card',
  '55': 'Incorrect PIN',
  '57': 'Transaction Not Permitted',
  '61': 'Exceeds Withdrawal Limit',
  '62': 'Restricted Card',
  '63': 'Security Violation',
  '65': 'Activity Limit Exceeded',
  '91': 'Issuer Unavailable',
  '96': 'System Malfunction',
};

export const PROCESSING_CODE_LABELS: Record<string, string> = {
  '000000': 'Purchase',
  '010000': 'Cash Withdrawal',
  '200000': 'Refund',
  '090000': 'Purchase with Cashback',
  '310000': 'Balance Inquiry',
  '400000': 'Transfer',
  '500000': 'Payment',
};

export const MTI_REQUEST_MAP: Record<string, string> = {
  '0100': '0110',
  '0200': '0210',
  '0400': '0410',
  '0800': '0810',
};
